"""
OperaMind — Operations Agent
==============================
Framework : LangGraph 0.4+ (cyclic monitoring loop, interrupt for alerts)
Model     : claude-sonnet-4-6
Purpose   : Monitors workflows, tracks KPIs, detects SLA breaches,
            coordinates teams, generates automated reports, sends alerts.

pip install langgraph langchain-anthropic anthropic python-dotenv schedule

ENV: ANTHROPIC_API_KEY, SLACK_BOT_TOKEN, NOTION_TOKEN
"""
from __future__ import annotations
import os, json, datetime, random
from typing import Annotated, TypedDict, Literal
from dotenv import load_dotenv

from langchain_anthropic import ChatAnthropic
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from langchain_core.tools import tool
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from langgraph.checkpoint.memory import MemorySaver
from langgraph.prebuilt import ToolNode

load_dotenv()
llm = ChatAnthropic(model="claude-sonnet-4-6", max_tokens=2048, temperature=0.1)

class OpsState(TypedDict):
    messages: Annotated[list, add_messages]
    monitoring_scope: str
    alerts_triggered: list[str]
    reports_generated: list[str]
    last_check: str

# ── Tools ─────────────────────────────────────────────────────────────────

@tool
def fetch_kpis(department: str, period: str = "today") -> dict:
    """
    Fetch real-time KPI data for a department.
    department: 'support' | 'sales' | 'finance' | 'ops' | 'all'
    period: 'today' | 'this_week' | 'this_month'
    """
    print(f"[KPI] Fetching {department} metrics for {period}")
    # Production: pull from your BI tool / database / API
    kpis = {
        "support": {
            "open_tickets": 47, "resolved_today": 32, "avg_response_time_min": 4.2,
            "sla_breaches": 3, "csat": 4.6, "escalations": 5,
        },
        "sales": {
            "leads_today": 28, "demos_booked": 6, "pipeline_value": 142_000,
            "deals_closed": 2, "conversion_rate": 0.21, "avg_deal_size": 4_800,
        },
        "finance": {
            "invoices_pending": 12, "overdue_invoices": 3, "cash_position": 284_000,
            "burn_rate_monthly": 48_000, "runway_months": 5.9,
        },
        "ops": {
            "active_workflows": 24, "failed_workflows": 1, "sla_compliance_pct": 94.2,
            "team_utilization_pct": 87, "blockers_flagged": 2,
        },
    }
    if department == "all":
        return {"period": period, "kpis": kpis, "fetched_at": datetime.datetime.utcnow().isoformat()}
    return {"department": department, "period": period, "kpis": kpis.get(department, {})}

@tool
def check_sla_compliance(team: str) -> dict:
    """
    Check SLA compliance for a team. Returns breaches, at-risk items, and compliance %.
    """
    print(f"[SLA] Checking compliance for {team}")
    # Production: query Jira / project management tool
    breaches = [
        {"ticket_id": "TKT-1204", "type": "First response", "breached_by_mins": 45, "assignee": "Support Team"},
        {"ticket_id": "TKT-1198", "type": "Resolution", "breached_by_hrs": 2.5, "assignee": "Support Team"},
    ]
    at_risk = [
        {"ticket_id": "TKT-1211", "type": "First response", "time_remaining_mins": 12, "assignee": "Support Team"},
    ]
    return {
        "team": team,
        "compliance_pct": 94.2,
        "breaches": breaches,
        "at_risk": at_risk,
        "total_active_tickets": 47,
        "checked_at": datetime.datetime.utcnow().isoformat(),
    }

@tool
def generate_ops_report(
    report_type: Literal["daily_standup", "weekly_kpi", "sla_summary", "executive_brief"],
    period: str,
    include_departments: list[str],
) -> str:
    """
    Generate an operations report. Returns Markdown-formatted report.
    """
    print(f"[REPORT] Generating {report_type} for {period}")
    timestamp = datetime.datetime.utcnow().isoformat()

    return f"""
# {report_type.replace('_', ' ').title()} — {period}
*Generated by OperaMind Ops Agent · {timestamp}*

## Departments Covered
{', '.join(include_departments)}

## Key Highlights
- ✅ Support SLA compliance: 94.2% (target: 95%)
- ⚠️  3 SLA breaches today — escalation triggered
- ✅ Sales pipeline: $142,000 (↑ 12% vs last week)
- ⚠️  Finance: 3 overdue invoices require action
- ✅ All workflows running (1 minor failure — auto-retried)

## Alerts Raised
- SLA breach: TKT-1204 (45 min overdue — first response)
- SLA at-risk: TKT-1211 (12 min remaining)
- Overdue invoices: $8,400 outstanding > 60 days

## Actions Taken
- Notified support manager via Slack (#ops-alerts)
- Auto-escalated TKT-1204 to senior agent
- Sent AP aging report to CFO

## Tomorrow's Priorities
- Review support SLA root cause
- Close 2 pending deals ($9,600 combined)
- Process 12 pending invoices
"""

@tool
def send_slack_alert(
    channel: str,
    message: str,
    urgency: Literal["info", "warning", "critical"] = "info",
    mention: str = "",
) -> dict:
    """
    Send an alert to a Slack channel.
    urgency: info (blue) | warning (yellow) | critical (red)
    """
    emoji = {"info": "ℹ️", "warning": "⚠️", "critical": "🚨"}.get(urgency, "ℹ️")
    full_msg = f"{emoji} {mention + ' ' if mention else ''}{message}"
    print(f"[SLACK] → #{channel}: {full_msg}")
    # Production: slack_sdk.WebClient(token=os.environ["SLACK_BOT_TOKEN"]).chat_postMessage(...)
    return {
        "sent": True,
        "channel": channel,
        "urgency": urgency,
        "timestamp": datetime.datetime.utcnow().isoformat(),
    }

@tool
def assign_task(
    task_title: str,
    assignee: str,
    due_date: str,
    project: str,
    priority: Literal["low", "medium", "high", "urgent"] = "medium",
    description: str = "",
) -> dict:
    """
    Create and assign a task in Notion / Jira / Asana.
    """
    print(f"[TASK] Assigning '{task_title}' to {assignee} in {project}")
    # Production: notion_client.pages.create(...) or jira.create_issue(...)
    return {
        "task_id": f"TASK-{random.randint(1000,9999)}",
        "title": task_title,
        "assignee": assignee,
        "due_date": due_date,
        "project": project,
        "priority": priority,
        "url": f"https://notion.so/operamind/{task_title.lower().replace(' ', '-')}",
        "created_at": datetime.datetime.utcnow().isoformat(),
    }

@tool
def monitor_workflow_health(workflow_name: str = "all") -> dict:
    """
    Check the health of automated workflows and pipelines.
    Returns status, failures, and auto-retry results.
    """
    print(f"[MONITOR] Checking workflow health: {workflow_name}")
    return {
        "total_workflows": 24,
        "healthy": 23,
        "failed": 1,
        "failed_workflows": [
            {
                "name": "invoice-sync-quickbooks",
                "last_failure": datetime.datetime.utcnow().isoformat(),
                "error": "API rate limit exceeded",
                "auto_retried": True,
                "retry_scheduled": (datetime.datetime.utcnow() + datetime.timedelta(minutes=15)).isoformat(),
            }
        ],
        "uptime_pct": 99.2,
        "checked_at": datetime.datetime.utcnow().isoformat(),
    }

@tool
def forecast_capacity(
    team: str,
    current_pipeline_items: int,
    avg_hours_per_item: float,
    team_size: int,
    available_hours_per_person: float = 35.0,
) -> dict:
    """
    Capacity planning tool. Calculates team utilization and forecasts
    when a team will hit overload based on current pipeline.
    """
    print(f"[CAPACITY] Forecasting capacity for {team}")
    total_hours_needed = current_pipeline_items * avg_hours_per_item
    total_hours_available = team_size * available_hours_per_person
    utilization_pct = (total_hours_needed / total_hours_available) * 100 if total_hours_available > 0 else 0
    over_capacity = utilization_pct > 90

    if utilization_pct <= 70:
        recommended_action = "Team has healthy capacity — consider taking on stretch projects."
        weeks_until_overload = 8
    elif utilization_pct <= 90:
        recommended_action = "Approaching capacity limits — defer non-critical work and monitor closely."
        weeks_until_overload = 3
    else:
        recommended_action = "OVER CAPACITY — redistribute work, hire contractors, or descope immediately."
        weeks_until_overload = 0

    return {
        "team": team,
        "current_pipeline_items": current_pipeline_items,
        "total_hours_needed": round(total_hours_needed, 1),
        "total_hours_available": round(total_hours_available, 1),
        "utilization_pct": round(utilization_pct, 1),
        "over_capacity": over_capacity,
        "recommended_action": recommended_action,
        "weeks_until_overload": weeks_until_overload,
        "forecasted_at": datetime.datetime.utcnow().isoformat(),
    }

@tool
def detect_bottlenecks(department: str) -> dict:
    """
    Detect operational bottlenecks in a department.
    Analyzes workflow queues, handoff delays, and resource contention.
    """
    print(f"[BOTTLENECK] Scanning {department} for bottlenecks")
    # Production: query workflow engine, analyze queue depths and cycle times
    bottleneck_data = {
        "support": {
            "bottleneck_detected": True,
            "bottleneck_description": "Tier-2 escalation queue backing up — avg wait 4.5 hours",
            "affected_workflows": ["ticket-escalation", "customer-followup", "sla-tracking"],
            "avg_delay_hours": 4.5,
            "root_cause": "Only 2 Tier-2 agents available; 3rd agent on PTO since Monday",
            "recommended_fix": "Temporarily assign senior Tier-1 agent to handle Tier-2 overflow",
        },
        "sales": {
            "bottleneck_detected": True,
            "bottleneck_description": "Contract approval taking 3x longer than SLA",
            "affected_workflows": ["deal-closing", "contract-review", "revenue-recognition"],
            "avg_delay_hours": 18.0,
            "root_cause": "Legal review backlog — 8 contracts awaiting single reviewer",
            "recommended_fix": "Engage external legal counsel for standard contract templates",
        },
        "finance": {
            "bottleneck_detected": False,
            "bottleneck_description": "No significant bottlenecks detected",
            "affected_workflows": [],
            "avg_delay_hours": 0.0,
            "root_cause": "N/A",
            "recommended_fix": "Continue current processes — next review in 7 days",
        },
    }
    result = bottleneck_data.get(department, {
        "bottleneck_detected": False,
        "bottleneck_description": f"No data available for {department}",
        "affected_workflows": [],
        "avg_delay_hours": 0.0,
        "root_cause": "Department not yet instrumented",
        "recommended_fix": f"Set up workflow monitoring for {department}",
    })
    result["department"] = department
    result["scanned_at"] = datetime.datetime.utcnow().isoformat()
    return result

@tool
def schedule_recurring_sync(
    meeting_title: str,
    attendees: list[str],
    frequency: Literal["daily", "weekly", "biweekly"],
    preferred_time: str,
    duration_minutes: int,
) -> dict:
    """
    Schedule a recurring sync meeting. Creates a calendar event series
    and notifies all attendees.
    """
    print(f"[CALENDAR] Scheduling '{meeting_title}' ({frequency}) at {preferred_time}")
    # Production: Google Calendar API / Outlook Graph API
    freq_days = {"daily": 1, "weekly": 7, "biweekly": 14}
    next_date = datetime.date.today() + datetime.timedelta(days=freq_days.get(frequency, 7))
    return {
        "calendar_event_id": f"EVT-{random.randint(10000, 99999)}",
        "meeting_title": meeting_title,
        "attendees": attendees,
        "frequency": frequency,
        "preferred_time": preferred_time,
        "duration_minutes": duration_minutes,
        "next_occurrence": f"{next_date.isoformat()}T{preferred_time}",
        "series_created": True,
        "created_at": datetime.datetime.utcnow().isoformat(),
    }

@tool
def track_okrs(quarter: str) -> dict:
    """
    Track OKR progress for a given quarter (e.g. 'Q2 2026').
    Returns objectives, key results, and overall quarter health.
    """
    print(f"[OKR] Tracking OKRs for {quarter}")
    # Production: pull from OKR tool (Lattice, Ally.io, Notion, etc.)
    return {
        "quarter": quarter,
        "objectives": [
            {
                "title": "Improve customer satisfaction to best-in-class",
                "key_results": [
                    {"description": "Achieve CSAT score of 4.8+", "progress_pct": 72, "status": "on_track"},
                    {"description": "Reduce avg response time to < 3 min", "progress_pct": 58, "status": "at_risk"},
                    {"description": "Zero P1 SLA breaches for 30 consecutive days", "progress_pct": 40, "status": "behind"},
                ],
            },
            {
                "title": "Scale revenue pipeline by 40%",
                "key_results": [
                    {"description": "Increase qualified leads to 200/month", "progress_pct": 85, "status": "on_track"},
                    {"description": "Close $500K in new ARR", "progress_pct": 62, "status": "on_track"},
                ],
            },
            {
                "title": "Achieve operational excellence across all teams",
                "key_results": [
                    {"description": "Automate 80% of recurring ops tasks", "progress_pct": 45, "status": "at_risk"},
                    {"description": "Reduce workflow failure rate to < 0.5%", "progress_pct": 90, "status": "on_track"},
                    {"description": "Complete cross-team process documentation", "progress_pct": 30, "status": "behind"},
                ],
            },
        ],
        "overall_quarter_health": "at_risk",
        "tracked_at": datetime.datetime.utcnow().isoformat(),
    }

@tool
def create_incident_report(
    incident_type: Literal["system_outage", "data_breach", "sla_critical", "service_degradation"],
    severity: Literal["P1", "P2", "P3"],
    description: str,
    affected_systems: list[str],
) -> dict:
    """
    Create an incident report and initiate incident response workflow.
    Notifies stakeholders, updates status page, and creates a war room.
    """
    print(f"[INCIDENT] Creating {severity} incident report: {incident_type}")
    incident_id = f"INC-{random.randint(10000, 99999)}"

    stakeholder_map = {
        "P1": ["CTO", "VP Engineering", "On-Call Lead", "Customer Success Lead"],
        "P2": ["VP Engineering", "On-Call Lead", "Team Lead"],
        "P3": ["Team Lead", "On-Call Engineer"],
    }
    resolution_map = {
        "P1": "2 hours",
        "P2": "8 hours",
        "P3": "48 hours",
    }

    return {
        "incident_id": incident_id,
        "incident_type": incident_type,
        "severity": severity,
        "description": description,
        "affected_systems": affected_systems,
        "status_page_updated": severity in ("P1", "P2"),
        "stakeholders_notified": stakeholder_map.get(severity, []),
        "war_room_link": f"https://meet.google.com/operamind-{incident_id.lower()}",
        "estimated_resolution": resolution_map.get(severity, "Unknown"),
        "created_at": datetime.datetime.utcnow().isoformat(),
    }

# ── System prompt ──────────────────────────────────────────────────────────

SYSTEM_PROMPT = """You are OperaMind's AI Operations Employee.

You are the nervous system of the business. Your job is to:
1. Monitor all workflows and KPIs continuously
2. Detect SLA breaches and at-risk tickets — alert immediately via Slack
3. Generate daily standup digests and weekly KPI reports automatically
4. Assign tasks when bottlenecks are found
5. Monitor workflow health — report failures and retries
6. Forecast team capacity and flag overloaded teams before they break
7. Detect bottlenecks across departments and recommend fixes
8. Schedule recurring syncs and coordination meetings
9. Track OKR progress and report quarter health
10. Create incident reports for outages and critical issues — notify stakeholders and open war rooms

Priority order:
1. CRITICAL alerts (SLA breaches, workflow failures, cash flow risks) → send Slack immediately
2. WARNING items → include in next digest, assign tasks
3. INFO → include in weekly report

Always check all departments before generating a report.
Current date: {date} {time}
"""

# ── Graph ──────────────────────────────────────────────────────────────────

tools = [fetch_kpis, check_sla_compliance, generate_ops_report,
         send_slack_alert, assign_task, monitor_workflow_health,
         forecast_capacity, detect_bottlenecks, schedule_recurring_sync,
         track_okrs, create_incident_report]
tool_node = ToolNode(tools)
llm_with_tools = llm.bind_tools(tools)

def ops_agent(state: OpsState) -> OpsState:
    now = datetime.datetime.utcnow()
    system = SYSTEM_PROMPT.format(date=now.date(), time=now.strftime("%H:%M UTC"))
    response = llm_with_tools.invoke([SystemMessage(content=system)] + state["messages"])
    return {"messages": [response]}

def router(state: OpsState) -> Literal["tools", "end"]:
    last = state["messages"][-1]
    return "tools" if (hasattr(last, "tool_calls") and last.tool_calls) else "end"

checkpointer = MemorySaver()
builder = StateGraph(OpsState)
builder.add_node("agent", ops_agent)
builder.add_node("tools", tool_node)
builder.add_edge(START, "agent")
builder.add_conditional_edges("agent", router, {"tools": "tools", "end": END})
builder.add_edge("tools", "agent")
graph = builder.compile(checkpointer=checkpointer)

# ── Public API ─────────────────────────────────────────────────────────────

def run_morning_check(scope: str = "all") -> dict:
    """Run the daily operations morning check — called automatically at 8 AM."""
    config = {"configurable": {"thread_id": f"morning_{datetime.date.today()}"}}
    prompt = (
        f"Run the morning operations check for {scope}.\n"
        "1. Fetch all KPIs\n"
        "2. Check SLA compliance for support\n"
        "3. Monitor workflow health\n"
        "4. Send any critical alerts to #ops-alerts on Slack\n"
        "5. Generate a daily standup digest and send to #team-standup"
    )
    result = graph.invoke(
        {"messages": [HumanMessage(content=prompt)], "monitoring_scope": scope,
         "alerts_triggered": [], "reports_generated": [],
         "last_check": datetime.datetime.utcnow().isoformat()},
        config=config,
    )
    final = next((m for m in reversed(result["messages"])
                  if isinstance(m, AIMessage) and not m.tool_calls), None)
    return {"ops_summary": final.content if final else "Check complete."}

def trigger_alert(alert_type: str, details: str) -> dict:
    """Manually trigger an operations alert (called by other agents or webhooks)."""
    config = {"configurable": {"thread_id": f"alert_{datetime.datetime.utcnow().timestamp():.0f}"}}
    prompt = f"ALERT TRIGGERED: {alert_type}\nDetails: {details}\nTake appropriate action immediately."
    result = graph.invoke(
        {"messages": [HumanMessage(content=prompt)], "monitoring_scope": "alert",
         "alerts_triggered": [], "reports_generated": [],
         "last_check": datetime.datetime.utcnow().isoformat()},
        config=config,
    )
    final = next((m for m in reversed(result["messages"])
                  if isinstance(m, AIMessage) and not m.tool_calls), None)
    return {"alert_handled": True, "response": final.content if final else "Alert processed."}


if __name__ == "__main__":
    result = run_morning_check("all")
    print("\nOPS AGENT MORNING CHECK:\n", result["ops_summary"])
