"""
OperaMind — Operations Agent
==============================
Framework : LangGraph 0.4+ (cyclic monitoring loop, interrupt for alerts)
Model     : claude-sonnet-4-6
Purpose   : Monitors workflows, tracks KPIs, detects SLA breaches,
            coordinates teams, generates automated reports, sends alerts.

pip install langgraph langchain-anthropic anthropic python-dotenv schedule

ENV: ANTHROPIC_API_KEY, SLACK_BOT_TOKEN, NOTION_TOKEN
"""
from __future__ import annotations
import os, json, datetime, random
from typing import Annotated, TypedDict, Literal
from dotenv import load_dotenv

from langchain_anthropic import ChatAnthropic
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from langchain_core.tools import tool
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from langgraph.checkpoint.memory import MemorySaver
from langgraph.prebuilt import ToolNode

load_dotenv()
llm = ChatAnthropic(model="claude-sonnet-4-6", max_tokens=2048, temperature=0.1)

class OpsState(TypedDict):
    messages: Annotated[list, add_messages]
    monitoring_scope: str
    alerts_triggered: list[str]
    reports_generated: list[str]
    last_check: str

# ── Tools ─────────────────────────────────────────────────────────────────

@tool
def fetch_kpis(department: str, period: str = "today") -> dict:
    """
    Fetch real-time KPI data for a department.
    department: 'support' | 'sales' | 'finance' | 'ops' | 'all'
    period: 'today' | 'this_week' | 'this_month'
    """
    print(f"[KPI] Fetching {department} metrics for {period}")
    # Production: pull from your BI tool / database / API
    kpis = {
        "support": {
            "open_tickets": 47, "resolved_today": 32, "avg_response_time_min": 4.2,
            "sla_breaches": 3, "csat": 4.6, "escalations": 5,
        },
        "sales": {
            "leads_today": 28, "demos_booked": 6, "pipeline_value": 142_000,
            "deals_closed": 2, "conversion_rate": 0.21, "avg_deal_size": 4_800,
        },
        "finance": {
            "invoices_pending": 12, "overdue_invoices": 3, "cash_position": 284_000,
            "burn_rate_monthly": 48_000, "runway_months": 5.9,
        },
        "ops": {
            "active_workflows": 24, "failed_workflows": 1, "sla_compliance_pct": 94.2,
            "team_utilization_pct": 87, "blockers_flagged": 2,
        },
    }
    if department == "all":
        return {"period": period, "kpis": kpis, "fetched_at": datetime.datetime.utcnow().isoformat()}
    return {"department": department, "period": period, "kpis": kpis.get(department, {})}

@tool
def check_sla_compliance(team: str) -> dict:
    """
    Check SLA compliance for a team. Returns breaches, at-risk items, and compliance %.
    """
    print(f"[SLA] Checking compliance for {team}")
    # Production: query Jira / project management tool
    breaches = [
        {"ticket_id": "TKT-1204", "type": "First response", "breached_by_mins": 45, "assignee": "Support Team"},
        {"ticket_id": "TKT-1198", "type": "Resolution", "breached_by_hrs": 2.5, "assignee": "Support Team"},
    ]
    at_risk = [
        {"ticket_id": "TKT-1211", "type": "First response", "time_remaining_mins": 12, "assignee": "Support Team"},
    ]
    return {
        "team": team,
        "compliance_pct": 94.2,
        "breaches": breaches,
        "at_risk": at_risk,
        "total_active_tickets": 47,
        "checked_at": datetime.datetime.utcnow().isoformat(),
    }

@tool
def generate_ops_report(
    report_type: Literal["daily_standup", "weekly_kpi", "sla_summary", "executive_brief"],
    period: str,
    include_departments: list[str],
) -> str:
    """
    Generate an operations report. Returns Markdown-formatted report.
    """
    print(f"[REPORT] Generating {report_type} for {period}")
    timestamp = datetime.datetime.utcnow().isoformat()

    return f"""
# {report_type.replace('_', ' ').title()} — {period}
*Generated by OperaMind Ops Agent · {timestamp}*

## Departments Covered
{', '.join(include_departments)}

## Key Highlights
- ✅ Support SLA compliance: 94.2% (target: 95%)
- ⚠️  3 SLA breaches today — escalation triggered
- ✅ Sales pipeline: $142,000 (↑ 12% vs last week)
- ⚠️  Finance: 3 overdue invoices require action
- ✅ All workflows running (1 minor failure — auto-retried)

## Alerts Raised
- SLA breach: TKT-1204 (45 min overdue — first response)
- SLA at-risk: TKT-1211 (12 min remaining)
- Overdue invoices: $8,400 outstanding > 60 days

## Actions Taken
- Notified support manager via Slack (#ops-alerts)
- Auto-escalated TKT-1204 to senior agent
- Sent AP aging report to CFO

## Tomorrow's Priorities
- Review support SLA root cause
- Close 2 pending deals ($9,600 combined)
- Process 12 pending invoices
"""

@tool
def send_slack_alert(
    channel: str,
    message: str,
    urgency: Literal["info", "warning", "critical"] = "info",
    mention: str = "",
) -> dict:
    """
    Send an alert to a Slack channel.
    urgency: info (blue) | warning (yellow) | critical (red)
    """
    emoji = {"info": "ℹ️", "warning": "⚠️", "critical": "🚨"}.get(urgency, "ℹ️")
    full_msg = f"{emoji} {mention + ' ' if mention else ''}{message}"
    print(f"[SLACK] → #{channel}: {full_msg}")
    # Production: slack_sdk.WebClient(token=os.environ["SLACK_BOT_TOKEN"]).chat_postMessage(...)
    return {
        "sent": True,
        "channel": channel,
        "urgency": urgency,
        "timestamp": datetime.datetime.utcnow().isoformat(),
    }

@tool
def assign_task(
    task_title: str,
    assignee: str,
    due_date: str,
    project: str,
    priority: Literal["low", "medium", "high", "urgent"] = "medium",
    description: str = "",
) -> dict:
    """
    Create and assign a task in Notion / Jira / Asana.
    """
    print(f"[TASK] Assigning '{task_title}' to {assignee} in {project}")
    # Production: notion_client.pages.create(...) or jira.create_issue(...)
    return {
        "task_id": f"TASK-{random.randint(1000,9999)}",
        "title": task_title,
        "assignee": assignee,
        "due_date": due_date,
        "project": project,
        "priority": priority,
        "url": f"https://notion.so/operamind/{task_title.lower().replace(' ', '-')}",
        "created_at": datetime.datetime.utcnow().isoformat(),
    }

@tool
def monitor_workflow_health(workflow_name: str = "all") -> dict:
    """
    Check the health of automated workflows and pipelines.
    Returns status, failures, and auto-retry results.
    """
    print(f"[MONITOR] Checking workflow health: {workflow_name}")
    return {
        "total_workflows": 24,
        "healthy": 23,
        "failed": 1,
        "failed_workflows": [
            {
                "name": "invoice-sync-quickbooks",
                "last_failure": datetime.datetime.utcnow().isoformat(),
                "error": "API rate limit exceeded",
                "auto_retried": True,
                "retry_scheduled": (datetime.datetime.utcnow() + datetime.timedelta(minutes=15)).isoformat(),
            }
        ],
        "uptime_pct": 99.2,
        "checked_at": datetime.datetime.utcnow().isoformat(),
    }

# ── System prompt ──────────────────────────────────────────────────────────

SYSTEM_PROMPT = """You are OperaMind's AI Operations Employee.

You are the nervous system of the business. Your job is to:
1. Monitor all workflows and KPIs continuously
2. Detect SLA breaches and at-risk tickets — alert immediately via Slack
3. Generate daily standup digests and weekly KPI reports automatically
4. Assign tasks when bottlenecks are found
5. Monitor workflow health — report failures and retries

Priority order:
1. CRITICAL alerts (SLA breaches, workflow failures, cash flow risks) → send Slack immediately
2. WARNING items → include in next digest, assign tasks
3. INFO → include in weekly report

Always check all departments before generating a report.
Current date: {date} {time}
"""

# ── Graph ──────────────────────────────────────────────────────────────────

tools = [fetch_kpis, check_sla_compliance, generate_ops_report,
         send_slack_alert, assign_task, monitor_workflow_health]
tool_node = ToolNode(tools)
llm_with_tools = llm.bind_tools(tools)

def ops_agent(state: OpsState) -> OpsState:
    now = datetime.datetime.utcnow()
    system = SYSTEM_PROMPT.format(date=now.date(), time=now.strftime("%H:%M UTC"))
    response = llm_with_tools.invoke([SystemMessage(content=system)] + state["messages"])
    return {"messages": [response]}

def router(state: OpsState) -> Literal["tools", "end"]:
    last = state["messages"][-1]
    return "tools" if (hasattr(last, "tool_calls") and last.tool_calls) else "end"

checkpointer = MemorySaver()
builder = StateGraph(OpsState)
builder.add_node("agent", ops_agent)
builder.add_node("tools", tool_node)
builder.add_edge(START, "agent")
builder.add_conditional_edges("agent", router, {"tools": "tools", "end": END})
builder.add_edge("tools", "agent")
graph = builder.compile(checkpointer=checkpointer)

# ── Public API ─────────────────────────────────────────────────────────────

def run_morning_check(scope: str = "all") -> dict:
    """Run the daily operations morning check — called automatically at 8 AM."""
    config = {"configurable": {"thread_id": f"morning_{datetime.date.today()}"}}
    prompt = (
        f"Run the morning operations check for {scope}.\n"
        "1. Fetch all KPIs\n"
        "2. Check SLA compliance for support\n"
        "3. Monitor workflow health\n"
        "4. Send any critical alerts to #ops-alerts on Slack\n"
        "5. Generate a daily standup digest and send to #team-standup"
    )
    result = graph.invoke(
        {"messages": [HumanMessage(content=prompt)], "monitoring_scope": scope,
         "alerts_triggered": [], "reports_generated": [],
         "last_check": datetime.datetime.utcnow().isoformat()},
        config=config,
    )
    final = next((m for m in reversed(result["messages"])
                  if isinstance(m, AIMessage) and not m.tool_calls), None)
    return {"ops_summary": final.content if final else "Check complete."}

def trigger_alert(alert_type: str, details: str) -> dict:
    """Manually trigger an operations alert (called by other agents or webhooks)."""
    config = {"configurable": {"thread_id": f"alert_{datetime.datetime.utcnow().timestamp():.0f}"}}
    prompt = f"ALERT TRIGGERED: {alert_type}\nDetails: {details}\nTake appropriate action immediately."
    result = graph.invoke(
        {"messages": [HumanMessage(content=prompt)], "monitoring_scope": "alert",
         "alerts_triggered": [], "reports_generated": [],
         "last_check": datetime.datetime.utcnow().isoformat()},
        config=config,
    )
    final = next((m for m in reversed(result["messages"])
                  if isinstance(m, AIMessage) and not m.tool_calls), None)
    return {"alert_handled": True, "response": final.content if final else "Alert processed."}


if __name__ == "__main__":
    result = run_morning_check("all")
    print("\nOPS AGENT MORNING CHECK:\n", result["ops_summary"])
